name: Run Tests PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore: [ '.gitignore', '.swift-format', 'README.md', 'LICENSE' ]

jobs:
  run_tests_pr:
    runs-on: macos-14
    steps:
    - name: Set XCode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Checkout project including tags
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run tests
      run: swift test
